### DISCUSSION TITLE
docker-support 제안

### DISCUSSION THREAD

**Discussion by youngsu5582** [woowacourse-teams/2024-corea#368] [General]
저희 로컬 서버 application.yml 은 Datasource 를 `MySQL` 로 지정하고 있습니다.

- runtimeOnly 로 'com.mysql:mysql-connector-j' 'com.h2database:h2' 두개를 혼용시켜 사용하기 애매한 점
( dev,prod 서버는 h2를 쓰지 않는데도 runtimeOnly 로 들어감 )
- build.gradle 을 따로 파고 지정하기 귀찮은 점

그렇기에, 로컬에서 구현할 때 저희가 직접 DB를 켜서 구동해야 합니다.
모두한테 똑같이 설정되어 있어야 하기에 ( database.url ) 도커를 사용하는데 저희가 직접 docker-compose 를 커맨드로 쳐서 구동을 해야 합니다.

### Docker-Compose-Support

스프링 에서 docker-compose 를 자체적으로 지원 해줍니다.

#### 지원해준다?

자동으로 실행해서 container 를 구동하고
ConnectionDetail 과 같이 추상화를 해 연결을 해줍니다.

<img width="587" alt="image" src="https://github.com/user-attachments/assets/1f232357-560c-47a1-81eb-6334cd32d2ac">

이와 같이 여러개의 Detail 지원

```
  docker:
    compose:
      lifecycle-management: start_and_stop
      start:
        command: up
      stop:
        command: down
```
application.yml 에 docker 옵션 지정
- lifecycle-management : 컨테이너 생명 주기 관리 ( start_and_stop 은 JVM 이 꺼지면 커넥션 역시 같이 종료 )

#### 단점?

어차피 Docker Desktop 은 구동이 되어야 합니다.
prod 와 dev 에서는 docker-compose-support 을 쓰지 않아도 의존성이 들어가게 됩니다.

---

우리가, 도커나 DB 를 크게 신경쓰지 않아도 된다는 점 + 서버에 따라 자동으로 키고 꺼진다 라는 점이 핵심일 거 같습니다.
의견 부담없이 주세용 🙂
